### ISSUE TITLE
Cape EEPROM

### ISSUE THREAD

**Issue by mwelling** [pmezydlo/BeagleBone_serial_cape#4]
It is recommend that the capes have a EEPROM (24c256) for auto-detection.

**Comment by pmezydlo** [comment]
I corrected, EEPROM is on a cape

**Comment by mwelling** [comment]
Good. You need to make sure the EEPROM also has a .1uF bypass capacitor.

**Comment by pmezydlo** [comment]
I added it, Thanks for review Michael
